FROM python:3.8-slim

RUN mkdir /opt/cookingchrono

RUN python -m pip install --upgrade pip

RUN python -m pip install poetry
WORKDIR /opt/cookingchrono

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry install --no-root -vvv

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install --yes libmtdev1 libgl1-mesa-glx
RUN DEBIAN_FRONTEND=noninteractive apt install --yes libxrender1

ENTRYPOINT ["poetry"]
